# Generated by Django 2.2 on 2019-04-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190423_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantstatistics',
            name='plantstage',
            field=models.CharField(db_column='plantStage', default='firststage', max_length=20),
        ),
    ]
