# Generated by Django 2.2 on 2019-04-25 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190423_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
