# Generated by Django 2.1.7 on 2019-05-12 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190425_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorinform',
            name='monitorid',
        ),
        migrations.AddField(
            model_name='monitorinform',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitorinform',
            name='mtime',
            field=models.DateTimeField(db_column='MTime', default=datetime.datetime.now),
        ),
    ]
