# Generated by Django 2.1.2 on 2019-01-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_viewparam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLog',
        ),
        migrations.DeleteModel(
            name='ViewParam',
        ),
    ]
