# Generated by Django 2.1.2 on 2019-01-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190127_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem', models.CharField(max_length=8)),
                ('pre', models.CharField(max_length=8)),
                ('hum', models.CharField(max_length=8)),
                ('led', models.CharField(max_length=8)),
                ('lasttime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem', models.CharField(max_length=8)),
                ('pre', models.CharField(max_length=8)),
                ('hum', models.CharField(max_length=8)),
                ('led', models.CharField(max_length=5)),
                ('lasttime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
