# Generated by Django 2.1.2 on 2019-01-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_changelog_viewparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='hum',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='led',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='pre',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='tem',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='viewparam',
            name='hum',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='viewparam',
            name='pre',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='viewparam',
            name='tem',
            field=models.CharField(max_length=5),
        ),
    ]
