# Generated by Django 2.1.2 on 2019-03-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_changelog_viewparam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLog',
        ),
        migrations.DeleteModel(
            name='ViewParam',
        ),
    ]
