# Generated by Django 2.1.2 on 2019-03-15 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_changelogs_viewparams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLogs',
        ),
        migrations.DeleteModel(
            name='ViewParams',
        ),
    ]
