# Generated by Django 2.1.2 on 2019-03-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_changelog_viewparam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLog',
        ),
        migrations.DeleteModel(
            name='ViewParam',
        ),
    ]
